import { Button } from "@/components/ui/button";
import { Info } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const RewardsStep = () => {
  return (
    <div className="space-y-6">
      <div className="space-y-4">
        <h2 className="text-2xl font-semibold text-[#1A1F2C]">My rewards</h2>
        <p className="text-base text-[#1A1F2C]">Make these something your customers will love!</p>
        <div className="flex items-center gap-2 text-sm">
          <span className="text-[#1A1F2C]">Note: In-app vouchers are generated by default. If you don't want these, please proceed by adding rewards and then</span>
          <a href="#" className="text-blue-500 hover:underline">contact us</a>
          <Info className="h-4 w-4 text-[#1A1F2C]" />
        </div>
      </div>

      <Dialog>
        <DialogTrigger asChild>
          <Button className="w-full justify-center gap-2">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M8 3.33337V12.6667" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M3.33331 8H12.6666" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            Add reward
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Add a reward</DialogTitle>
          </DialogHeader>
          <div className="space-y-6 py-4">
            <div className="space-y-4">
              <Label>Reward type*</Label>
              <div className="flex gap-4">
                <div className="flex flex-col items-center gap-2 rounded-lg border border-red-500 p-4">
                  <div className="h-12 w-12 bg-[#E7F9F1]">
                    <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <rect width="48" height="48" rx="8" fill="#E7F9F1"/>
                      <path d="M31 24.5C31 23.837 30.7366 23.2011 30.2678 22.7322C29.7989 22.2634 29.163 22 28.5 22H20.5C19.837 22 19.2011 22.2634 18.7322 22.7322C18.2634 23.2011 18 23.837 18 24.5V29.5C18 30.163 18.2634 30.7989 18.7322 31.2678C19.2011 31.7366 19.837 32 20.5 32H28.5C29.163 32 29.7989 31.7366 30.2678 31.2678C30.7366 30.7989 31 30.163 31 29.5V24.5Z" stroke="#12B76A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      <path d="M27 22V19.5C27 18.837 26.7366 18.2011 26.2678 17.7322C25.7989 17.2634 25.163 17 24.5 17H20.5C19.837 17 19.2011 17.2634 18.7322 17.7322C18.2634 18.2011 18 18.837 18 19.5V22" stroke="#12B76A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </div>
                  <span className="text-sm font-medium">Main</span>
                </div>
                <div className="flex flex-col items-center gap-2 rounded-lg border p-4">
                  <div className="h-12 w-12 bg-[#FFF9E5]">
                    <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <rect width="48" height="48" rx="8" fill="#FFF9E5"/>
                      <path d="M31 24.5C31 23.837 30.7366 23.2011 30.2678 22.7322C29.7989 22.2634 29.163 22 28.5 22H20.5C19.837 22 19.2011 22.2634 18.7322 22.7322C18.2634 23.2011 18 23.837 18 24.5V29.5C18 30.163 18.2634 30.7989 18.7322 31.2678C19.2011 31.7366 19.837 32 20.5 32H28.5C29.163 32 29.7989 31.7366 30.2678 31.2678C30.7366 30.7989 31 30.163 31 29.5V24.5Z" stroke="#F79009" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      <path d="M27 22V19.5C27 18.837 26.7366 18.2011 26.2678 17.7322C25.7989 17.2634 25.163 17 24.5 17H20.5C19.837 17 19.2011 17.2634 18.7322 17.7322C18.2634 18.2011 18 18.837 18 19.5V22" stroke="#F79009" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </div>
                  <span className="text-sm font-medium">Sign Up</span>
                </div>
                <div className="flex flex-col items-center gap-2 rounded-lg border p-4">
                  <div className="h-12 w-12 bg-[#EEF4FF]">
                    <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <rect width="48" height="48" rx="8" fill="#EEF4FF"/>
                      <path d="M31 24.5C31 23.837 30.7366 23.2011 30.2678 22.7322C29.7989 22.2634 29.163 22 28.5 22H20.5C19.837 22 19.2011 22.2634 18.7322 22.7322C18.2634 23.2011 18 23.837 18 24.5V29.5C18 30.163 18.2634 30.7989 18.7322 31.2678C19.2011 31.7366 19.837 32 20.5 32H28.5C29.163 32 29.7989 31.7366 30.2678 31.2678C30.7366 30.7989 31 30.163 31 29.5V24.5Z" stroke="#444CE7" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      <path d="M27 22V19.5C27 18.837 26.7366 18.2011 26.2678 17.7322C25.7989 17.2634 25.163 17 24.5 17H20.5C19.837 17 19.2011 17.2634 18.7322 17.7322C18.2634 18.2011 18 18.837 18 19.5V22" stroke="#444CE7" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </div>
                  <span className="text-sm font-medium">Interim</span>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <Label>Reward name*</Label>
              <Input placeholder="Free coffee" />
              <div className="text-sm text-gray-500">after 6 stamps</div>
            </div>
            <div className="space-y-2">
              <Label>Settings</Label>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm">Expiry</span>
                  <div className="h-6 w-11 rounded-full bg-gray-200"></div>
                </div>
              </div>
            </div>
            <Button className="w-full">Save reward</Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};