import { Button } from "@/components/ui/button";
import { Info } from "lucide-react";

export const RewardsStep = () => {
  return (
    <div className="space-y-6">
      <div className="space-y-4">
        <h2 className="text-2xl font-semibold text-[#1A1F2C]">My rewards</h2>
        <p className="text-base text-[#1A1F2C]">Make these something your customers will love!</p>
        <div className="flex items-center gap-2 text-sm">
          <span className="text-[#1A1F2C]">Note: In-app vouchers are generated by default. If you don't want these, please proceed by adding rewards and then</span>
          <a href="#" className="text-blue-500 hover:underline">contact us</a>
          <Info className="h-4 w-4 text-[#1A1F2C]" />
        </div>
      </div>

      <Button variant="outline" className="w-full justify-center gap-2 border-[#FF4B55] text-[#FF4B55] hover:bg-[#FF4B55] hover:text-white">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M8 3.33337V12.6667" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          <path d="M3.33331 8H12.6666" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
        Add reward
      </Button>
    </div>
  );
};